version: "2"
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - /data/db
    restart: unless-stopped
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "80:3000"
    volumes:
      - ".:/usr/src/app"
    restart: on-failure
    links:
      - mongo
