version: "2"
services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - /data/db
    restart: on-failure

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 80:3000
    volumes:
      - ".:/app"
    restart: on-failure
    environment:
      - PORT=3000
    depends_on:
      - mongo
