version: "2"
services:
  mongo:
    image: mongo:latest
    ports:
      - 27017
    volumes:
      - /data/db
    restart: on-failure
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:3000
    volumes:
      - ".:/usr/src/app"
    restart: on-failure
    depends_on:
      - mongo
